# Generated by Django 6.0.1 on 2026-01-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='badges',
            field=models.JSONField(max_length=100, null=True),
        ),
    ]
