# Generated by Django 6.0.1 on 2026-01-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_project_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='badges',
            field=models.JSONField(),
        ),
    ]
