# Generated by Django 6.0.1 on 2026-01-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_badges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='badges',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
