# Generated by Django 5.2.10 on 2026-01-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_github_link_project_live_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField()),
                ('message', models.TextField()),
            ],
        ),
    ]
